// Seed data for the mock backend. Swap mockApi.js import for serverApi.js to use real Express server.

function daysAgo(days, hours = 0) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hours);
  return d.toISOString();
}

function daysFromNow(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export const seedUsers = [
  {
    id: "u1",
    name: "You",
    headline: "Full-Stack Developer · Building things with React & Node.js",
    university: "Shivaji University",
    program: "B.Tech Computer Science",
    year: "3rd Year",
    location: "Kolhapur, MH",
    bio: "Passionate about building products that solve real problems. Currently exploring full-stack development and open-source contributions.",
    skills: ["React", "Node.js", "MongoDB", "JavaScript", "Git"],
    skillProficiencies: [
      { skill: "React", level: "Intermediate" },
      { skill: "Node.js", level: "Intermediate" },
      { skill: "MongoDB", level: "Beginner" },
      { skill: "JavaScript", level: "Intermediate" },
      { skill: "Git", level: "Beginner" },
    ],
    interests: ["Web Development", "UI/UX", "Open Source"],
    projects: [
      { id: "proj1", name: "Campus Network App", description: "A professional networking platform for higher education students built with React and Node.js.", tech: ["React", "Node.js", "MongoDB"], githubUrl: "https://github.com", liveUrl: "", date: "2026" },
      { id: "proj2", name: "Study Planner", description: "A React app to help students organise their study sessions and track progress.", tech: ["React", "LocalStorage"], githubUrl: "https://github.com", liveUrl: "", date: "2025" },
    ],
    certifications: [
      { id: "cert1", name: "Meta Front-End Developer Certificate", issuer: "Coursera / Meta", date: "Jan 2026", url: "https://coursera.org" },
    ],
    achievements: ["1st place at departmental hackathon 2025", "Dean's List — Semester 5"],
    links: { github: "https://github.com", linkedin: "", portfolio: "" },
    avatarColor: "#2F5233",
    onboardingComplete: true,
    credits: 45,
    isSelf: true,
  },
  {
    id: "u2",
    name: "Priya Nandakumar",
    headline: "CS Junior · Building accessible ML tools",
    university: "Shivaji University",
    program: "B.Tech Computer Science",
    year: "3rd Year",
    location: "Pune, MH",
    bio: "Currently researching low-resource NLP for regional languages. Always up for pairing on a side project.",
    skills: ["Python", "PyTorch", "TensorFlow", "Public Speaking", "SQL"],
    skillProficiencies: [
      { skill: "Python", level: "Advanced" },
      { skill: "PyTorch", level: "Intermediate" },
    ],
    interests: ["AI/ML", "Data Science", "Research"],
    projects: [
      { id: "proj3", name: "Marathi NLP Classifier", description: "Fine-tuned transformer model for Marathi text classification with under 2,000 labeled examples.", tech: ["Python", "PyTorch", "HuggingFace"], githubUrl: "https://github.com", liveUrl: "", date: "2026" },
    ],
    certifications: [
      { id: "cert2", name: "Deep Learning Specialization", issuer: "Coursera / DeepLearning.AI", date: "Mar 2025", url: "" },
    ],
    achievements: ["Published at department research symposium"],
    links: { github: "https://github.com", linkedin: "", portfolio: "" },
    avatarColor: "#9C7D1B",
    credits: 68,
  },
  {
    id: "u3",
    name: "Aarav Deshmukh",
    headline: "Final year Mechanical · Formula Student captain",
    university: "COEP Technological University",
    program: "B.Tech Mechanical Engineering",
    year: "4th Year",
    location: "Pune, MH",
    bio: "Leading our Formula Student aero package this season. Looking for mentors in vehicle dynamics.",
    skills: ["SolidWorks", "CFD", "AutoCAD", "Team Leadership", "ANSYS"],
    skillProficiencies: [
      { skill: "SolidWorks", level: "Advanced" },
      { skill: "CFD", level: "Intermediate" },
    ],
    interests: ["Engineering", "Leadership", "Automotive"],
    projects: [
      { id: "proj4", name: "FS Aero Package 2025", description: "Full aerodynamics package for Formula Student race car — passed wind tunnel validation within 4%.", tech: ["SolidWorks", "ANSYS Fluent"], githubUrl: "", liveUrl: "", date: "2025" },
    ],
    certifications: [],
    achievements: ["Formula Student India — Top 5 Aero", "Best Design Award — COEP Tech Fest"],
    links: { github: "", linkedin: "", portfolio: "" },
    avatarColor: "#6B4F3B",
    credits: 82,
  },
  {
    id: "u4",
    name: "Dr. Neha Kulkarni",
    headline: "Alumni Mentor · Ex-Amazon Applied Scientist",
    university: "Shivaji University",
    program: "Faculty — School of Computing",
    year: "Faculty",
    location: "Bengaluru, KA",
    bio: "Ex-Amazon applied scientist, now teaching. I mentor 3–4 students each semester on applied ML projects.",
    skills: ["Mentorship", "Applied ML", "Career Guidance", "Python", "Statistics"],
    skillProficiencies: [
      { skill: "Applied ML", level: "Advanced" },
      { skill: "Python", level: "Advanced" },
    ],
    interests: ["Mentorship", "AI/ML", "Research"],
    projects: [],
    certifications: [],
    achievements: ["Best Paper Award — NeurIPS Workshop"],
    links: { github: "https://github.com", linkedin: "https://linkedin.com", portfolio: "" },
    avatarColor: "#4A7052",
    credits: 100,
  },
  {
    id: "u5",
    name: "Rohan Iyer",
    headline: "Sophomore · Product design enthusiast",
    university: "MIT-WPU",
    program: "B.Des Product Design",
    year: "2nd Year",
    location: "Pune, MH",
    bio: "Learning UX research methods. Just wrapped a usability study on campus navigation apps.",
    skills: ["Figma", "User Research", "Prototyping", "Adobe XD"],
    skillProficiencies: [
      { skill: "Figma", level: "Intermediate" },
      { skill: "User Research", level: "Beginner" },
    ],
    interests: ["UI/UX", "Product Design"],
    projects: [
      { id: "proj5", name: "Campus Nav App Study", description: "12-person usability study of campus navigation apps. Found users trust apps showing building entrances over outlines.", tech: ["Figma", "Maze"], githubUrl: "", liveUrl: "", date: "2026" },
    ],
    certifications: [],
    achievements: [],
    links: { github: "", linkedin: "", portfolio: "https://rohan.design" },
    avatarColor: "#C9A227",
    credits: 41,
  },
  {
    id: "u6",
    name: "Aisha Khan",
    headline: "Data Science · Kaggle Competitions",
    university: "VIT Pune",
    program: "B.Tech IT",
    year: "3rd Year",
    location: "Nashik, MH",
    bio: "Kaggle competitor. Interested in building interpretable ML models for healthcare.",
    skills: ["Python", "Pandas", "Scikit-learn", "SQL", "R"],
    skillProficiencies: [{ skill: "Python", level: "Advanced" }],
    interests: ["Data Science", "AI/ML", "Healthcare"],
    projects: [],
    certifications: [{ id: "cert3", name: "Google Data Analytics", issuer: "Coursera / Google", date: "Dec 2025", url: "" }],
    achievements: ["Top 5% Kaggle — Tabular Playground Series"],
    links: { github: "https://github.com", linkedin: "", portfolio: "" },
    avatarColor: "#C9A227",
    credits: 55,
  },
  {
    id: "u7",
    name: "Dev Sharma",
    headline: "Cybersecurity student · CTF player",
    university: "IIT Bombay",
    program: "B.Tech CSE",
    year: "2nd Year",
    location: "Mumbai, MH",
    bio: "CTF enthusiast. Currently learning web security and network protocols.",
    skills: ["Linux", "Python", "Networking", "Ethical Hacking", "Bash"],
    skillProficiencies: [{ skill: "Linux", level: "Intermediate" }, { skill: "Python", level: "Intermediate" }],
    interests: ["Cybersecurity"],
    projects: [],
    certifications: [{ id: "cert4", name: "CompTIA Security+ (in progress)", issuer: "CompTIA", date: "2026", url: "" }],
    achievements: ["HackTheBox — Pro Hacker rank"],
    links: { github: "https://github.com", linkedin: "", portfolio: "" },
    avatarColor: "#6B4F3B",
    credits: 38,
  },
  {
    id: "u8",
    name: "Meera Joshi",
    headline: "Commerce Graduate · Startup Finance & Strategy",
    university: "Symbiosis College",
    program: "BBA Finance",
    year: "3rd Year",
    location: "Pune, MH",
    bio: "Building a startup growth tracker tool as my final year project. Interested in fintech.",
    skills: ["Excel", "Financial Modeling", "Business Analysis", "Tally", "PowerPoint"],
    skillProficiencies: [],
    interests: ["Business", "Leadership", "Fintech"],
    projects: [{ id: "proj6", name: "Startup Growth Tracker", description: "Excel + Python dashboard to track startup KPIs and runway projections.", tech: ["Python", "Excel", "Pandas"], githubUrl: "", liveUrl: "", date: "2026" }],
    certifications: [],
    achievements: [],
    links: { github: "", linkedin: "", portfolio: "" },
    avatarColor: "#9C7D1B",
    credits: 30,
  },
  {
    id: "u9",
    name: "Arjun Patel",
    headline: "Android Dev · Kotlin & Firebase",
    university: "NMIMS University",
    program: "B.Tech IT",
    year: "4th Year",
    location: "Mumbai, MH",
    bio: "Published 2 apps on Play Store. Currently building a smart campus app for my college.",
    skills: ["Kotlin", "Android", "Firebase", "REST APIs", "XML"],
    skillProficiencies: [
      { skill: "Kotlin", level: "Advanced" },
      { skill: "Android", level: "Advanced" },
      { skill: "Firebase", level: "Intermediate" },
    ],
    interests: ["Mobile Development", "Web Development"],
    projects: [
      { id: "proj7", name: "NMIMS Campus App", description: "Smart campus app with timetable, canteen menu, and lost-and-found. 500+ downloads.", tech: ["Kotlin", "Firebase", "Android"], githubUrl: "https://github.com", liveUrl: "", date: "2025" },
    ],
    certifications: [],
    achievements: ["Google Play Store — 500+ downloads"],
    links: { github: "https://github.com", linkedin: "", portfolio: "" },
    avatarColor: "#2F5233",
    credits: 72,
  },
  {
    id: "u10",
    name: "Simran Kaur",
    headline: "Communication Design · Brand & Visual Identity",
    university: "NID Ahmedabad",
    program: "B.Des Communication Design",
    year: "3rd Year",
    location: "Ahmedabad, GJ",
    bio: "Designing for social impact. Currently running a campaign for rural digital literacy.",
    skills: ["Illustrator", "InDesign", "Typography", "Branding", "Canva"],
    skillProficiencies: [{ skill: "Illustrator", level: "Advanced" }, { skill: "Branding", level: "Intermediate" }],
    interests: ["UI/UX", "Communication", "Social Impact"],
    projects: [
      { id: "proj8", name: "Rural Digital Literacy Campaign", description: "Complete brand identity and communication materials for an NGO digital literacy initiative.", tech: ["Illustrator", "InDesign"], githubUrl: "", liveUrl: "", date: "2026" },
    ],
    certifications: [],
    achievements: ["NID Design Award — Communication Category"],
    links: { github: "", linkedin: "", portfolio: "https://simran.design" },
    avatarColor: "#4A7052",
    credits: 61,
  },
];

export const seedPosts = [
  {
    id: "p1",
    authorId: "u4",
    content: "Reminder for my mentees: the applied-ML showcase submission window opens Monday. Bring a working prototype, not just slides — I care more about what broke than what worked.",
    tag: "Mentorship",
    createdAt: daysAgo(0, 3),
    likes: ["u2", "u3"],
    comments: [
      { id: "c1", authorId: "u2", content: "Noted! Finishing our eval notebook this weekend.", createdAt: daysAgo(0, 1) },
    ],
  },
  {
    id: "p2",
    authorId: "u3",
    content: "Our Formula Student aero package passed wind-tunnel validation today. Six weeks of CFD iterations later, the numbers finally matched simulation within 4%. Grateful for the whole team.",
    tag: "Milestone",
    createdAt: daysAgo(1, 4),
    likes: ["u1", "u4", "u5"],
    comments: [],
  },
  {
    id: "p3",
    authorId: "u2",
    content: "Publishing a short write-up on fine-tuning small models for Marathi text classification with under 2,000 labeled examples. Sharing here first — feedback welcome.",
    tag: "Research",
    createdAt: daysAgo(2, 1),
    likes: ["u4"],
    comments: [
      { id: "c2", authorId: "u5", content: "Would love to read this once it's up!", createdAt: daysAgo(1, 6) },
    ],
  },
  {
    id: "p4",
    authorId: "u5",
    content: "Ran a 12-person usability study on three campus navigation apps this week. Biggest finding: nobody trusts an app that doesn't show building entrances. Full report going in my portfolio.",
    tag: "Project",
    createdAt: daysAgo(3, 2),
    likes: ["u2"],
    comments: [],
  },
  {
    id: "p5",
    authorId: "u9",
    content: "Just hit 500 downloads on the NMIMS Campus App! Started this as a weekend hack — now the canteen uses it to post daily menus. Wild how quickly something useful spreads on a campus.",
    tag: "Milestone",
    createdAt: daysAgo(4, 1),
    likes: ["u1", "u2", "u4", "u6"],
    comments: [
      { id: "c3", authorId: "u4", content: "Great example of building for your immediate community first. Congrats!", createdAt: daysAgo(3, 22) },
    ],
  },
  {
    id: "p6",
    authorId: "u6",
    content: "Top 5% on Kaggle's latest tabular competition. Used a simple gradient boosting pipeline with careful feature engineering — no fancy deep learning. Clean data beats clever models every time.",
    tag: "Milestone",
    createdAt: daysAgo(5, 6),
    likes: ["u2", "u4"],
    comments: [],
  },
];

export const seedConnections = {
  connected: ["u4"],
  pending: ["u3"],
  incoming: ["u2"],
};

export const seedOpportunities = [
  { id: "o1", title: "Frontend Intern — React + TypeScript", organization: "Postman", type: "Internship", location: "Bengaluru", isRemote: true, deadline: daysFromNow(20), description: "Join Postman's growth team to build internal tools and improve developer experience. Work closely with senior engineers on features shipped to millions of developers.", skills: ["React", "TypeScript", "REST APIs"], applyUrl: "https://postman.com/careers" },
  { id: "o2", title: "Smart India Hackathon 2025", organization: "Ministry of Education", type: "Hackathon", location: "Pan-India", isRemote: false, deadline: daysFromNow(35), description: "National-level hackathon open to all college students. Work on real government problem statements across health, agriculture, and education.", skills: ["Problem Solving", "Any tech stack"], applyUrl: "https://sih.gov.in" },
  { id: "o3", title: "Data Science Intern", organization: "Flipkart", type: "Internship", location: "Bengaluru", isRemote: false, deadline: daysFromNow(15), description: "Build recommendation models and A/B testing frameworks for Flipkart's e-commerce platform.", skills: ["Python", "SQL", "Pandas", "ML"], applyUrl: "https://flipkart.com/careers" },
  { id: "o4", title: "UX Design Workshop — Google", organization: "Google India", type: "Workshop", location: "Online", isRemote: true, deadline: daysFromNow(10), description: "3-day intensive workshop covering design thinking, user research, and Figma. Open to design students nationwide.", skills: ["Figma", "User Research", "Design Thinking"], applyUrl: "https://events.google.com" },
  { id: "o5", title: "KPIT Sparkle 2025", organization: "KPIT Technologies", type: "Competition", location: "Pune", isRemote: false, deadline: daysFromNow(45), description: "Annual technology innovation competition for engineering students. Build projects in EV, automation, and sustainable tech.", skills: ["Embedded Systems", "IoT", "Automotive"], applyUrl: "https://kpitsparkle.com" },
  { id: "o6", title: "AICTE National Scholarship for STEM", organization: "AICTE", type: "Scholarship", location: "Pan-India", isRemote: false, deadline: daysFromNow(60), description: "Merit-based scholarship for technically-excellent students. Covers tuition for the entire degree.", skills: ["Academic Excellence"], applyUrl: "https://aicte-india.org/scholarships" },
  { id: "o7", title: "Backend Engineering Intern", organization: "Razorpay", type: "Internship", location: "Bengaluru", isRemote: false, deadline: daysFromNow(25), description: "Build high-throughput payment processing microservices. Exposure to distributed systems and fintech.", skills: ["Node.js", "PostgreSQL", "Redis"], applyUrl: "https://razorpay.com/jobs" },
  { id: "o8", title: "Webinar: Breaking Into Product Management", organization: "Product School India", type: "Webinar", location: "Online", isRemote: true, deadline: daysFromNow(5), description: "Panel discussion with PMs from Google, Amazon, and Indian startups.", skills: ["Communication", "Product Thinking"], applyUrl: "https://productschool.com/events" },
  { id: "o9", title: "HackTheBox Campus CTF", organization: "HackTheBox", type: "Competition", location: "Online", isRemote: true, deadline: daysFromNow(30), description: "48-hour CTF for college teams. Real-world security challenges in web, crypto, forensics, and reverse engineering.", skills: ["Cybersecurity", "Linux", "Python"], applyUrl: "https://hackthebox.com/university" },
  { id: "o10", title: "ML Research Intern — IIT Bombay", organization: "IIT Bombay AI Lab", type: "Internship", location: "Mumbai", isRemote: false, deadline: daysFromNow(40), description: "Research internship in NLP and computer vision. Work alongside PhD students on published research.", skills: ["Python", "PyTorch", "Research"], applyUrl: "https://iitb.ac.in/research" },
];

export const seedResources = [
  { id: "r1", title: "The Odin Project — Full Stack JS", category: "Web Development", description: "Free curriculum covering HTML, CSS, JavaScript, Node.js, React, and databases from beginner to job-ready.", difficulty: "Beginner", estimatedHours: 120, url: "https://www.theodinproject.com", tags: ["HTML", "CSS", "JavaScript", "React"] },
  { id: "r2", title: "CS50x — Intro to Computer Science", category: "Programming", description: "Harvard's legendary intro to CS. Covers C, Python, SQL, and web development.", difficulty: "Beginner", estimatedHours: 80, url: "https://cs50.harvard.edu/x", tags: ["C", "Python", "Algorithms"] },
  { id: "r3", title: "Fast.ai — Practical Deep Learning", category: "AI/ML", description: "Top-down deep learning with PyTorch. Used by researchers worldwide. Best practical ML course available free.", difficulty: "Intermediate", estimatedHours: 40, url: "https://course.fast.ai", tags: ["Python", "PyTorch", "Deep Learning"] },
  { id: "r4", title: "SQL for Data Analysis", category: "Database", description: "Hands-on SQL course by Mode Analytics. Covers JOINs, subqueries, and window functions for real analysis.", difficulty: "Beginner", estimatedHours: 20, url: "https://mode.com/sql-tutorial", tags: ["SQL", "Data Analysis"] },
  { id: "r5", title: "NeetCode DSA Roadmap", category: "Data Structures", description: "Structured DSA roadmap with video explanations and LeetCode problems by pattern. Best interview prep resource.", difficulty: "Intermediate", estimatedHours: 60, url: "https://neetcode.io/roadmap", tags: ["DSA", "LeetCode", "Algorithms"] },
  { id: "r6", title: "Communication Skills Specialization", category: "Communication", description: "5-course Coursera specialization from University of Michigan covering writing, speaking, and presentations.", difficulty: "Beginner", estimatedHours: 30, url: "https://www.coursera.org/specializations/communication-skills", tags: ["Communication", "Writing"] },
  { id: "r7", title: "Harvard Resume Writing Guide", category: "Resume Building", description: "Harvard OCS guide to compelling resumes and cover letters for internship and job applications.", difficulty: "Beginner", estimatedHours: 3, url: "https://ocs.fas.harvard.edu/resumes-cvs", tags: ["Resume", "Job Search"] },
  { id: "r8", title: "Figma UI Design — Zero to Hero", category: "UI/UX", description: "Complete Figma course: components, auto-layout, prototyping, and design systems.", difficulty: "Beginner", estimatedHours: 25, url: "https://www.figma.com/resources/learn-design", tags: ["Figma", "UI Design"] },
  { id: "r9", title: "Tech Interview Handbook", category: "Career Development", description: "LinkedIn optimization, cold outreach, interviews, salary negotiation — the complete career guide for students.", difficulty: "Beginner", estimatedHours: 5, url: "https://www.techinterviewhandbook.org", tags: ["Internship", "Job Search", "Networking"] },
  { id: "r10", title: "Kaggle Learn — Machine Learning", category: "Data Science", description: "Free mini-courses: pandas, ML fundamentals, feature engineering, and computer vision with Kaggle competitions.", difficulty: "Beginner", estimatedHours: 15, url: "https://www.kaggle.com/learn", tags: ["ML", "Python", "Pandas"] },
  { id: "r11", title: "PortSwigger Web Security Academy", category: "Cybersecurity", description: "Free web security training from Burp Suite creators. Covers XSS, SQL injection, authentication vulnerabilities.", difficulty: "Intermediate", estimatedHours: 50, url: "https://portswigger.net/web-security", tags: ["Security", "Web", "Ethical Hacking"] },
  { id: "r12", title: "Cracking the Coding Interview Prep", category: "Interview Prep", description: "Curated resources for FAANG and top startup interviews. Includes behavioral, system design, and coding practice.", difficulty: "Advanced", estimatedHours: 100, url: "https://www.techinterviewhandbook.org", tags: ["Interview", "DSA", "System Design"] },
];

export const seedNotifications = [
  { id: "n1", type: "connection_request", message: "Priya Nandakumar sent you a connection request.", read: false, link: "/network", fromUserId: "u2", createdAt: daysAgo(0, 2) },
  { id: "n2", type: "post_like", message: "Aarav Deshmukh liked your post.", read: false, link: "/feed", fromUserId: "u3", createdAt: daysAgo(0, 5) },
  { id: "n3", type: "connection_accepted", message: "Dr. Neha Kulkarni accepted your connection request.", read: true, link: "/profile/u4", fromUserId: "u4", createdAt: daysAgo(1, 3) },
  { id: "n4", type: "opportunity", message: "New opportunity: Frontend Intern at Postman — deadline in 20 days.", read: true, link: "/opportunities", fromUserId: null, createdAt: daysAgo(2, 0) },
  { id: "n5", type: "milestone", message: "🎉 You've added 5 skills to your profile! Keep growing.", read: true, link: "/profile", fromUserId: null, createdAt: daysAgo(3, 1) },
];

export const seedGoals = [
  { id: "g1", title: "Complete React Hooks deep dive", status: "completed", createdAt: daysAgo(14) },
  { id: "g2", title: "Build a full-stack MERN project", status: "in-progress", createdAt: daysAgo(7) },
  { id: "g3", title: "Apply to 3 internships before semester ends", status: "in-progress", createdAt: daysAgo(5) },
  { id: "g4", title: "Complete SQL course on Mode Analytics", status: "not-started", createdAt: daysAgo(2) },
];
